networks:
  jenkins:
    external: true

services:
  jenkins:
    image: jenkins-with-maven
    container_name: jenkins
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  nexus:
    image: sonatype/nexus3:3.37.3
    container_name: nexus
    ports:
      - 8081:8081
      - 5000:5000
    volumes:
      - nexus-data:/nexus-data
    networks:
      - jenkins

volumes:
  nexus-data:
  jenkins-data:
