networks:
  jenkins:
    external: true

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    restart: always

#  nexus:
#    image: sonatype/nexus3:3.37.3
#    container_name: nexus
#    ports:
#      - 8081:8081
#      - 5000:5000
#    networks:
#      - jenkins
#  app:
#    build: .
#    ports:
#      - 8080:8080
#    environment:
#      - NEXUS_URL=http://nexus:8081/repository/maven-releases
#    depends_on:
#      - nexus

volumes:
  #  nexus-data:
  jenkins-data:
